Changed REST API web framework & servlet container
fasten-project/fasten pull request #123
Opened 2020-11-18 17:16 UTC by marcomicera

## Intro

In #111 I discussed how switching from RESTeasy+Jetty to Spring+Tomcat (both servlets containers are embedded) could solve multiple problems at once. More specifically:

- Jetty timeouts #86 
- CDI not working (needed for unit testing) #87
- Unsupported concurrent requests #93

This PR contains such a switch, i.e., the web framework change and the servlet container change.
Endpoints (and their corresponding canned queries) are still the same.

## ✅ Achieved results

Following the same order:

- #86: users do not experience timeouts anymore.
  All the [endpoints that were causing Jetty to timeout](https://github.com/fasten-project/fasten/wiki/API-endpoints-for-Maven-projects#endpoints) now work, confirming that SQL queries were fine and that the problem was probably caused by some Jetty configuration.
- #87: CDI is now working.
  This is an [example](https://github.com/endocode/fasten/blob/200a8cbb8ece0d28b9822251a11d1e6d52fb78d2/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/BinaryModuleApi.java#L15-L16) of how a [service implementation](https://github.com/endocode/fasten/blob/200a8cbb8ece0d28b9822251a11d1e6d52fb78d2/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/impl/BinaryModuleApiServiceImpl.java#L9-L10) is injected by Spring Boot in a `@RestController`, as opposed to [statically initializing such a field](https://github.com/fasten-project/fasten/blob/d09da9d31fe9574a7876c9c4f2e102dd27fddccb/analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/api/mvn/BinaryModuleApi.java#L14).
  This can be exploited by future unit tests (#87).
- #93: I did not find a simple way to handle concurrent requests in Jetty rather than spawning threads manually https://github.com/fasten-project/fasten/issues/93#issuecomment-717196048.
  With Spring's embedded Tomcat, it'll be possible with a simple `server.tomcat.max-threads=20` in the [server configuration file](https://github.com/endocode/fasten/blob/c4935e593615cdf553f7f5e30356d945a39b1188/analyzer/restapi-plugin/src/main/resources/application.properties).

### Issues that would be closed when merging this PR

Closes #111, fixes #86 (just [linking this PR to the corresponding issues](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)...).

## ⚠️ Problem introduced by this switch

URI encoding is not enabled by default on Tomcat.
This causes the following endpoints:

- `/mvn/packages/{pkg}/{pkg_ver}/modules/{namespace}/metadata`
- `/mvn/packages/{pkg}/{pkg_ver}/modules/{namespace}/files`
- `/mvn/packages/{pkg}/{pkg_ver}/{fasten_uri}/metadata`

to fail as `{namespace}` and `{fasten_uri}` contain slashes and dollar signs.
I'll push a fix on top of this PR if I find a solution for this, **but those endpoints may change soon because of #114** anyway.

2020-11-20 13:12 UTC, marcomicera commented
@proksch should I add anyone else as a reviewer?

2020-11-22 19:35 UTC, romatallinn commented
@marcomicera there is one important endpoint missing; a simple retrieval of the package instance  _(forge, repo, etc)_.

2020-11-22 19:59 UTC, romatallinn commented
@marcomicera it'd be useful to have an endpoint `/{pkg}` that retrieves the `Package` instance _(forge, repo, etc)_ with the latest `PackageVersion` of it.

2020-11-22 20:16 UTC, romatallinn reviewed
@marcomicera it'd be useful to have an endpoint /{pkg} that retrieves the Package instance (forge, repo, etc) with the latest PackageVersion of it.

2020-11-22 20:16 UTC, romatallinn commented on analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/PackageApi.java
> +    }
- I believe the response of this endpoint should be flattened. We expect one PackageVersion entity always, but API returns it with a nested array, like `getPackageVersions` does, but it actually may have multiple instances.
- Is there a point in having pagination for such endpoints? I mean, again, we don't expect multiple instances in return, but just one specific?

2020-11-22 20:18 UTC, romatallinn reviewed
<comment deleted>

2020-11-22 20:23 UTC, romatallinn requested changes
<comment deleted>

2020-11-22 20:32 UTC, romatallinn commented on analyzer/restapi-plugin/src/main/java/eu/fasten/analyzer/restapiplugin/mvn/api/PackageApi.java
> +    }
Ok. Wrong PR. I'll move it to #80.

2020-11-23 14:27 UTC, merged